version: "3"
services:
  nginx:
    build:
      context: ./FE
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/k9d105.p.ssafy.io/fullchain.pem:/etc/ssl/cert.pem
      - /etc/letsencrypt/live/k9d105.p.ssafy.io/privkey.pem:/etc/ssl/key.pem
