version: "3"
services:
  nginx:
    build:
      context: ./FE
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/ggok2.duckdns.org/fullchain.pem:/etc/ssl/cert.pem
      - /etc/letsencrypt/live/ggok2.duckdns.org/privkey.pem:/etc/ssl/key.pem
